# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import Agency
    from ._models_py3 import AirAndPollen
    from ._models_py3 import AirQuality
    from ._models_py3 import Alert
    from ._models_py3 import AlertArea
    from ._models_py3 import AlertDescription
    from ._models_py3 import AlertDetail
    from ._models_py3 import AliasCreateResponse
    from ._models_py3 import AliasListItem
    from ._models_py3 import AliasListResponse
    from ._models_py3 import BatchRequestBody
    from ._models_py3 import BatchRequestBodyBatchItemsItem
    from ._models_py3 import BatchResponse
    from ._models_py3 import BatchResponseSummary
    from ._models_py3 import BooleanRuleObject
    from ._models_py3 import BooleanTypeStyleRule
    from ._models_py3 import BoundingBoxResponse
    from ._models_py3 import BoundingBoxResponseResult
    from ._models_py3 import BoundingBoxResponseSummary
    from ._models_py3 import BoundingBoxResult
    from ._models_py3 import BufferRequestBody
    from ._models_py3 import BufferResponse
    from ._models_py3 import BufferResponseSummary
    from ._models_py3 import ClosestPointResultEntry
    from ._models_py3 import CollectionDefinition
    from ._models_py3 import CollectionInfo
    from ._models_py3 import Color
    from ._models_py3 import Concentration
    from ._models_py3 import Content
    from ._models_py3 import ConversionListDetailInfo
    from ._models_py3 import ConversionListResponse
    from ._models_py3 import Coordinate
    from ._models_py3 import CoordinateAbbreviated
    from ._models_py3 import CopyrightBoundingResult
    from ._models_py3 import CopyrightCaptionResult
    from ._models_py3 import CopyrightTileResult
    from ._models_py3 import CopyrightWorldResult
    from ._models_py3 import Country
    from ._models_py3 import CountryRegion
    from ._models_py3 import CurrentAirQualityResponse
    from ._models_py3 import CurrentConditions
    from ._models_py3 import CurrentConditionsResponse
    from ._models_py3 import DailyAirQuality
    from ._models_py3 import DailyAirQualityForecastResponse
    from ._models_py3 import DailyForecast
    from ._models_py3 import DailyForecastResponse
    from ._models_py3 import DailyForecastSummary
    from ._models_py3 import DailyIndex
    from ._models_py3 import DailyIndicesResponse
    from ._models_py3 import DataSources
    from ._models_py3 import DataSourcesGeometry
    from ._models_py3 import DatasetDetailInfo
    from ._models_py3 import DatasetListResponse
    from ._models_py3 import DatasetSources
    from ._models_py3 import DayOrNight
    from ._models_py3 import DefinitionProperties
    from ._models_py3 import DegreeDaySummary
    from ._models_py3 import Description
    from ._models_py3 import Direction
    from ._models_py3 import ErrorAdditionalInfo
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorResponse
    from ._models_py3 import Fares
    from ._models_py3 import Feature
    from ._models_py3 import FeatureCollectionGeoJSON
    from ._models_py3 import FeatureGeoJSON
    from ._models_py3 import FeatureStateObject
    from ._models_py3 import FeatureStatesStructure
    from ._models_py3 import GeoJSONFeatureCollection
    from ._models_py3 import GeoJSONFeatureCollectionFeaturesItem
    from ._models_py3 import GeoJSONGeometry
    from ._models_py3 import GeofenceGeometry
    from ._models_py3 import GeofenceResponse
    from ._models_py3 import GetClosestPointResponse
    from ._models_py3 import GetClosestPointSummary
    from ._models_py3 import GetPointInPolygonResponse
    from ._models_py3 import GetPointInPolygonSummary
    from ._models_py3 import GreatCircleDistanceResponse
    from ._models_py3 import GreatCircleDistanceResponseResult
    from ._models_py3 import GreatCircleDistanceResponseSummary
    from ._models_py3 import HazardDetail
    from ._models_py3 import Hazards
    from ._models_py3 import HourlyAirQualityForecastResponse
    from ._models_py3 import HourlyForecast
    from ._models_py3 import HourlyForecastResponse
    from ._models_py3 import IanaId
    from ._models_py3 import Interval
    from ._models_py3 import IntervalSummary
    from ._models_py3 import IpAddressToLocationResult
    from ._models_py3 import ItineraryFare
    from ._models_py3 import ItineraryResult
    from ._models_py3 import LatestStatus
    from ._models_py3 import Leg
    from ._models_py3 import LegFare
    from ._models_py3 import LegPoint
    from ._models_py3 import Line
    from ._models_py3 import LineArrival
    from ._models_py3 import LineGroup
    from ._models_py3 import LineString
    from ._models_py3 import LineStringData
    from ._models_py3 import LinesResult
    from ._models_py3 import Link
    from ._models_py3 import LocalSource
    from ._models_py3 import LongRunningOperationResult
    from ._models_py3 import MapDataDetailInfo
    from ._models_py3 import MapDataListResponse
    from ._models_py3 import MetroAreaInfoResponse
    from ._models_py3 import MetroAreaResponse
    from ._models_py3 import MetroAreaResult
    from ._models_py3 import MinuteForecastResponse
    from ._models_py3 import MinuteForecastSummary
    from ._models_py3 import MultiPoint
    from ._models_py3 import MultiPointData
    from ._models_py3 import MultiPolygon
    from ._models_py3 import MultiPolygonData
    from ._models_py3 import Names
    from ._models_py3 import NearbyTransitResponse
    from ._models_py3 import Notification
    from ._models_py3 import NumberRuleObject
    from ._models_py3 import NumberTypeStyleRule
    from ._models_py3 import Pattern
    from ._models_py3 import PoiCategoryResponse
    from ._models_py3 import PoiCategoryResult
    from ._models_py3 import Point
    from ._models_py3 import PointArray
    from ._models_py3 import PointData
    from ._models_py3 import PointElevationResult
    from ._models_py3 import PointInPolygonResult
    from ._models_py3 import PointsResult
    from ._models_py3 import Pollutant
    from ._models_py3 import Polygon
    from ._models_py3 import PolygonData
    from ._models_py3 import PostClosestPointResponse
    from ._models_py3 import PostClosestPointSummary
    from ._models_py3 import PostPointInPolygonResponse
    from ._models_py3 import PostPointInPolygonSummary
    from ._models_py3 import PrecipitationSummary
    from ._models_py3 import PressureTendency
    from ._models_py3 import Price
    from ._models_py3 import QuarterDayForecast
    from ._models_py3 import QuarterDayForecastResponse
    from ._models_py3 import RangeObject
    from ._models_py3 import RealTimeArrivalResult
    from ._models_py3 import RealTimeArrivalsResponse
    from ._models_py3 import ReferenceTimeByCoordinates
    from ._models_py3 import ReferenceTimeById
    from ._models_py3 import Region
    from ._models_py3 import RegionCountry
    from ._models_py3 import RepresentativePoint
    from ._models_py3 import ReqClasses
    from ._models_py3 import ResultViewport
    from ._models_py3 import Root
    from ._models_py3 import RouteDirectionsRequestBody
    from ._models_py3 import RouteDirectionsRequestBodySupportingPoints
    from ._models_py3 import RouteDirectionsResponse
    from ._models_py3 import RouteDirectionsResult
    from ._models_py3 import RouteDirectionsSummary
    from ._models_py3 import RouteItineraryLeg
    from ._models_py3 import RouteMatrixRequestBody
    from ._models_py3 import RouteMatrixResponse
    from ._models_py3 import RouteMatrixResult
    from ._models_py3 import RouteMatrixResultResponse
    from ._models_py3 import RouteMatrixSummary
    from ._models_py3 import RouteOptimizedWaypoint
    from ._models_py3 import RouteRange
    from ._models_py3 import RouteRangeResponse
    from ._models_py3 import RouteResponseReport
    from ._models_py3 import RouteResponseReportEffectiveSetting
    from ._models_py3 import RouteResultGuidance
    from ._models_py3 import RouteResultInstruction
    from ._models_py3 import RouteResultInstructionGroup
    from ._models_py3 import RouteResultLeg
    from ._models_py3 import RouteResultLegSummary
    from ._models_py3 import RouteResultSection
    from ._models_py3 import RouteResultSectionTec
    from ._models_py3 import RouteResultSectionTecCause
    from ._models_py3 import SearchAddressResponse
    from ._models_py3 import SearchAddressResult
    from ._models_py3 import SearchAddressReverseCrossStreetResponse
    from ._models_py3 import SearchAddressReverseCrossStreetResult
    from ._models_py3 import SearchAddressReverseCrossStreetSummary
    from ._models_py3 import SearchAddressReverseResponse
    from ._models_py3 import SearchAddressReverseResult
    from ._models_py3 import SearchAddressReverseSummary
    from ._models_py3 import SearchAddressStructuredResponse
    from ._models_py3 import SearchAddressStructuredResult
    from ._models_py3 import SearchAddressStructuredSummary
    from ._models_py3 import SearchAddressSummary
    from ._models_py3 import SearchAlongRouteRequestBody
    from ._models_py3 import SearchAlongRouteResponse
    from ._models_py3 import SearchAlongRouteResult
    from ._models_py3 import SearchAlongRouteSummary
    from ._models_py3 import SearchFuzzyResponse
    from ._models_py3 import SearchFuzzyResult
    from ._models_py3 import SearchFuzzySummary
    from ._models_py3 import SearchGeometryResponse
    from ._models_py3 import SearchGeometryResult
    from ._models_py3 import SearchGeometrySummary
    from ._models_py3 import SearchInsideGeometryRequestBody
    from ._models_py3 import SearchNearbyResponse
    from ._models_py3 import SearchNearbyResult
    from ._models_py3 import SearchNearbySummary
    from ._models_py3 import SearchPoiCategoryResponse
    from ._models_py3 import SearchPoiCategoryResult
    from ._models_py3 import SearchPoiCategorySummary
    from ._models_py3 import SearchPoiResponse
    from ._models_py3 import SearchPoiResult
    from ._models_py3 import SearchPoiSummary
    from ._models_py3 import SearchPolygonResponse
    from ._models_py3 import SearchPolygonResult
    from ._models_py3 import SearchResultAddress
    from ._models_py3 import SearchResultAddressRanges
    from ._models_py3 import SearchResultEntryPoint
    from ._models_py3 import SearchResultPoi
    from ._models_py3 import SearchResultPoiBrand
    from ._models_py3 import SearchResultPoiCategorySet
    from ._models_py3 import SearchResultPoiClassification
    from ._models_py3 import SearchResultPoiClassificationName
    from ._models_py3 import SearchResultPoiOpeningHours
    from ._models_py3 import SearchResultPoiOpeningHoursTimeRange
    from ._models_py3 import SearchResultPoiOpeningHoursTimeRangeTime
    from ._models_py3 import SearchResultViewport
    from ._models_py3 import SearchSummaryGeoBias
    from ._models_py3 import SevereWeatherAlert
    from ._models_py3 import SevereWeatherAlertsResponse
    from ._models_py3 import SpatialCoordinate
    from ._models_py3 import StatesetCreatedResponse
    from ._models_py3 import StatesetGetResponse
    from ._models_py3 import StatesetInfoObject
    from ._models_py3 import StatesetListResponse
    from ._models_py3 import Step
    from ._models_py3 import Stop
    from ._models_py3 import StringRuleObject
    from ._models_py3 import StringTypeStyleRule
    from ._models_py3 import StyleRuleBase
    from ._models_py3 import StylesObject
    from ._models_py3 import SunGlare
    from ._models_py3 import TemperatureSummary
    from ._models_py3 import TemperatureSummaryPast12Hours
    from ._models_py3 import TemperatureSummaryPast24Hours
    from ._models_py3 import TemperatureSummaryPast6Hours
    from ._models_py3 import Tickets
    from ._models_py3 import TilesetDetailInfo
    from ._models_py3 import TilesetListResponse
    from ._models_py3 import TimeTransition
    from ._models_py3 import TimeZoneByCoordinates
    from ._models_py3 import TimezoneByCoordinatesResult
    from ._models_py3 import TimezoneById
    from ._models_py3 import TimezoneByIdResult
    from ._models_py3 import TimezoneEnumWindow
    from ._models_py3 import TimezoneIanaVersionResult
    from ._models_py3 import TrafficFlowSegmentResult
    from ._models_py3 import TrafficFlowSegmentResultFlowSegmentData
    from ._models_py3 import TrafficFlowSegmentResultFlowSegmentDataCoordinates
    from ._models_py3 import TrafficIncidentDetailResult
    from ._models_py3 import TrafficIncidentDetailResultTm
    from ._models_py3 import TrafficIncidentPoi
    from ._models_py3 import TrafficIncidentPoiCbl
    from ._models_py3 import TrafficIncidentPoiCtr
    from ._models_py3 import TrafficIncidentPoiP
    from ._models_py3 import TrafficIncidentTileResult
    from ._models_py3 import TrafficIncidentViewportResult
    from ._models_py3 import TrafficIncidentViewportResultViewpResp
    from ._models_py3 import TrafficIncidentViewportResultViewpRespTrafficState
    from ._models_py3 import TransitItineraryResponse
    from ._models_py3 import TransitLineInfoResponse
    from ._models_py3 import TransitObjectResult
    from ._models_py3 import TransitRouteResponse
    from ._models_py3 import TransitStopInfoResponse
    from ._models_py3 import TransitTypeResult
    from ._models_py3 import UploadDataAcceptedResponse
    from ._models_py3 import UploadDataResponse
    from ._models_py3 import Version
    from ._models_py3 import Waypoint
    from ._models_py3 import WeatherAlongRoutePrecipitation
    from ._models_py3 import WeatherAlongRouteResponse
    from ._models_py3 import WeatherAlongRouteSummary
    from ._models_py3 import WeatherUnit
    from ._models_py3 import WeatherUnitRange
    from ._models_py3 import Wind
    from ._models_py3 import WindDirection
    from ._models_py3 import WindSpeed
except (SyntaxError, ImportError):
    from ._models import Agency  # type: ignore
    from ._models import AirAndPollen  # type: ignore
    from ._models import AirQuality  # type: ignore
    from ._models import Alert  # type: ignore
    from ._models import AlertArea  # type: ignore
    from ._models import AlertDescription  # type: ignore
    from ._models import AlertDetail  # type: ignore
    from ._models import AliasCreateResponse  # type: ignore
    from ._models import AliasListItem  # type: ignore
    from ._models import AliasListResponse  # type: ignore
    from ._models import BatchRequestBody  # type: ignore
    from ._models import BatchRequestBodyBatchItemsItem  # type: ignore
    from ._models import BatchResponse  # type: ignore
    from ._models import BatchResponseSummary  # type: ignore
    from ._models import BooleanRuleObject  # type: ignore
    from ._models import BooleanTypeStyleRule  # type: ignore
    from ._models import BoundingBoxResponse  # type: ignore
    from ._models import BoundingBoxResponseResult  # type: ignore
    from ._models import BoundingBoxResponseSummary  # type: ignore
    from ._models import BoundingBoxResult  # type: ignore
    from ._models import BufferRequestBody  # type: ignore
    from ._models import BufferResponse  # type: ignore
    from ._models import BufferResponseSummary  # type: ignore
    from ._models import ClosestPointResultEntry  # type: ignore
    from ._models import CollectionDefinition  # type: ignore
    from ._models import CollectionInfo  # type: ignore
    from ._models import Color  # type: ignore
    from ._models import Concentration  # type: ignore
    from ._models import Content  # type: ignore
    from ._models import ConversionListDetailInfo  # type: ignore
    from ._models import ConversionListResponse  # type: ignore
    from ._models import Coordinate  # type: ignore
    from ._models import CoordinateAbbreviated  # type: ignore
    from ._models import CopyrightBoundingResult  # type: ignore
    from ._models import CopyrightCaptionResult  # type: ignore
    from ._models import CopyrightTileResult  # type: ignore
    from ._models import CopyrightWorldResult  # type: ignore
    from ._models import Country  # type: ignore
    from ._models import CountryRegion  # type: ignore
    from ._models import CurrentAirQualityResponse  # type: ignore
    from ._models import CurrentConditions  # type: ignore
    from ._models import CurrentConditionsResponse  # type: ignore
    from ._models import DailyAirQuality  # type: ignore
    from ._models import DailyAirQualityForecastResponse  # type: ignore
    from ._models import DailyForecast  # type: ignore
    from ._models import DailyForecastResponse  # type: ignore
    from ._models import DailyForecastSummary  # type: ignore
    from ._models import DailyIndex  # type: ignore
    from ._models import DailyIndicesResponse  # type: ignore
    from ._models import DataSources  # type: ignore
    from ._models import DataSourcesGeometry  # type: ignore
    from ._models import DatasetDetailInfo  # type: ignore
    from ._models import DatasetListResponse  # type: ignore
    from ._models import DatasetSources  # type: ignore
    from ._models import DayOrNight  # type: ignore
    from ._models import DefinitionProperties  # type: ignore
    from ._models import DegreeDaySummary  # type: ignore
    from ._models import Description  # type: ignore
    from ._models import Direction  # type: ignore
    from ._models import ErrorAdditionalInfo  # type: ignore
    from ._models import ErrorDetail  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import Fares  # type: ignore
    from ._models import Feature  # type: ignore
    from ._models import FeatureCollectionGeoJSON  # type: ignore
    from ._models import FeatureGeoJSON  # type: ignore
    from ._models import FeatureStateObject  # type: ignore
    from ._models import FeatureStatesStructure  # type: ignore
    from ._models import GeoJSONFeatureCollection  # type: ignore
    from ._models import GeoJSONFeatureCollectionFeaturesItem  # type: ignore
    from ._models import GeoJSONGeometry  # type: ignore
    from ._models import GeofenceGeometry  # type: ignore
    from ._models import GeofenceResponse  # type: ignore
    from ._models import GetClosestPointResponse  # type: ignore
    from ._models import GetClosestPointSummary  # type: ignore
    from ._models import GetPointInPolygonResponse  # type: ignore
    from ._models import GetPointInPolygonSummary  # type: ignore
    from ._models import GreatCircleDistanceResponse  # type: ignore
    from ._models import GreatCircleDistanceResponseResult  # type: ignore
    from ._models import GreatCircleDistanceResponseSummary  # type: ignore
    from ._models import HazardDetail  # type: ignore
    from ._models import Hazards  # type: ignore
    from ._models import HourlyAirQualityForecastResponse  # type: ignore
    from ._models import HourlyForecast  # type: ignore
    from ._models import HourlyForecastResponse  # type: ignore
    from ._models import IanaId  # type: ignore
    from ._models import Interval  # type: ignore
    from ._models import IntervalSummary  # type: ignore
    from ._models import IpAddressToLocationResult  # type: ignore
    from ._models import ItineraryFare  # type: ignore
    from ._models import ItineraryResult  # type: ignore
    from ._models import LatestStatus  # type: ignore
    from ._models import Leg  # type: ignore
    from ._models import LegFare  # type: ignore
    from ._models import LegPoint  # type: ignore
    from ._models import Line  # type: ignore
    from ._models import LineArrival  # type: ignore
    from ._models import LineGroup  # type: ignore
    from ._models import LineString  # type: ignore
    from ._models import LineStringData  # type: ignore
    from ._models import LinesResult  # type: ignore
    from ._models import Link  # type: ignore
    from ._models import LocalSource  # type: ignore
    from ._models import LongRunningOperationResult  # type: ignore
    from ._models import MapDataDetailInfo  # type: ignore
    from ._models import MapDataListResponse  # type: ignore
    from ._models import MetroAreaInfoResponse  # type: ignore
    from ._models import MetroAreaResponse  # type: ignore
    from ._models import MetroAreaResult  # type: ignore
    from ._models import MinuteForecastResponse  # type: ignore
    from ._models import MinuteForecastSummary  # type: ignore
    from ._models import MultiPoint  # type: ignore
    from ._models import MultiPointData  # type: ignore
    from ._models import MultiPolygon  # type: ignore
    from ._models import MultiPolygonData  # type: ignore
    from ._models import Names  # type: ignore
    from ._models import NearbyTransitResponse  # type: ignore
    from ._models import Notification  # type: ignore
    from ._models import NumberRuleObject  # type: ignore
    from ._models import NumberTypeStyleRule  # type: ignore
    from ._models import Pattern  # type: ignore
    from ._models import PoiCategoryResponse  # type: ignore
    from ._models import PoiCategoryResult  # type: ignore
    from ._models import Point  # type: ignore
    from ._models import PointArray  # type: ignore
    from ._models import PointData  # type: ignore
    from ._models import PointElevationResult  # type: ignore
    from ._models import PointInPolygonResult  # type: ignore
    from ._models import PointsResult  # type: ignore
    from ._models import Pollutant  # type: ignore
    from ._models import Polygon  # type: ignore
    from ._models import PolygonData  # type: ignore
    from ._models import PostClosestPointResponse  # type: ignore
    from ._models import PostClosestPointSummary  # type: ignore
    from ._models import PostPointInPolygonResponse  # type: ignore
    from ._models import PostPointInPolygonSummary  # type: ignore
    from ._models import PrecipitationSummary  # type: ignore
    from ._models import PressureTendency  # type: ignore
    from ._models import Price  # type: ignore
    from ._models import QuarterDayForecast  # type: ignore
    from ._models import QuarterDayForecastResponse  # type: ignore
    from ._models import RangeObject  # type: ignore
    from ._models import RealTimeArrivalResult  # type: ignore
    from ._models import RealTimeArrivalsResponse  # type: ignore
    from ._models import ReferenceTimeByCoordinates  # type: ignore
    from ._models import ReferenceTimeById  # type: ignore
    from ._models import Region  # type: ignore
    from ._models import RegionCountry  # type: ignore
    from ._models import RepresentativePoint  # type: ignore
    from ._models import ReqClasses  # type: ignore
    from ._models import ResultViewport  # type: ignore
    from ._models import Root  # type: ignore
    from ._models import RouteDirectionsRequestBody  # type: ignore
    from ._models import RouteDirectionsRequestBodySupportingPoints  # type: ignore
    from ._models import RouteDirectionsResponse  # type: ignore
    from ._models import RouteDirectionsResult  # type: ignore
    from ._models import RouteDirectionsSummary  # type: ignore
    from ._models import RouteItineraryLeg  # type: ignore
    from ._models import RouteMatrixRequestBody  # type: ignore
    from ._models import RouteMatrixResponse  # type: ignore
    from ._models import RouteMatrixResult  # type: ignore
    from ._models import RouteMatrixResultResponse  # type: ignore
    from ._models import RouteMatrixSummary  # type: ignore
    from ._models import RouteOptimizedWaypoint  # type: ignore
    from ._models import RouteRange  # type: ignore
    from ._models import RouteRangeResponse  # type: ignore
    from ._models import RouteResponseReport  # type: ignore
    from ._models import RouteResponseReportEffectiveSetting  # type: ignore
    from ._models import RouteResultGuidance  # type: ignore
    from ._models import RouteResultInstruction  # type: ignore
    from ._models import RouteResultInstructionGroup  # type: ignore
    from ._models import RouteResultLeg  # type: ignore
    from ._models import RouteResultLegSummary  # type: ignore
    from ._models import RouteResultSection  # type: ignore
    from ._models import RouteResultSectionTec  # type: ignore
    from ._models import RouteResultSectionTecCause  # type: ignore
    from ._models import SearchAddressResponse  # type: ignore
    from ._models import SearchAddressResult  # type: ignore
    from ._models import SearchAddressReverseCrossStreetResponse  # type: ignore
    from ._models import SearchAddressReverseCrossStreetResult  # type: ignore
    from ._models import SearchAddressReverseCrossStreetSummary  # type: ignore
    from ._models import SearchAddressReverseResponse  # type: ignore
    from ._models import SearchAddressReverseResult  # type: ignore
    from ._models import SearchAddressReverseSummary  # type: ignore
    from ._models import SearchAddressStructuredResponse  # type: ignore
    from ._models import SearchAddressStructuredResult  # type: ignore
    from ._models import SearchAddressStructuredSummary  # type: ignore
    from ._models import SearchAddressSummary  # type: ignore
    from ._models import SearchAlongRouteRequestBody  # type: ignore
    from ._models import SearchAlongRouteResponse  # type: ignore
    from ._models import SearchAlongRouteResult  # type: ignore
    from ._models import SearchAlongRouteSummary  # type: ignore
    from ._models import SearchFuzzyResponse  # type: ignore
    from ._models import SearchFuzzyResult  # type: ignore
    from ._models import SearchFuzzySummary  # type: ignore
    from ._models import SearchGeometryResponse  # type: ignore
    from ._models import SearchGeometryResult  # type: ignore
    from ._models import SearchGeometrySummary  # type: ignore
    from ._models import SearchInsideGeometryRequestBody  # type: ignore
    from ._models import SearchNearbyResponse  # type: ignore
    from ._models import SearchNearbyResult  # type: ignore
    from ._models import SearchNearbySummary  # type: ignore
    from ._models import SearchPoiCategoryResponse  # type: ignore
    from ._models import SearchPoiCategoryResult  # type: ignore
    from ._models import SearchPoiCategorySummary  # type: ignore
    from ._models import SearchPoiResponse  # type: ignore
    from ._models import SearchPoiResult  # type: ignore
    from ._models import SearchPoiSummary  # type: ignore
    from ._models import SearchPolygonResponse  # type: ignore
    from ._models import SearchPolygonResult  # type: ignore
    from ._models import SearchResultAddress  # type: ignore
    from ._models import SearchResultAddressRanges  # type: ignore
    from ._models import SearchResultEntryPoint  # type: ignore
    from ._models import SearchResultPoi  # type: ignore
    from ._models import SearchResultPoiBrand  # type: ignore
    from ._models import SearchResultPoiCategorySet  # type: ignore
    from ._models import SearchResultPoiClassification  # type: ignore
    from ._models import SearchResultPoiClassificationName  # type: ignore
    from ._models import SearchResultPoiOpeningHours  # type: ignore
    from ._models import SearchResultPoiOpeningHoursTimeRange  # type: ignore
    from ._models import SearchResultPoiOpeningHoursTimeRangeTime  # type: ignore
    from ._models import SearchResultViewport  # type: ignore
    from ._models import SearchSummaryGeoBias  # type: ignore
    from ._models import SevereWeatherAlert  # type: ignore
    from ._models import SevereWeatherAlertsResponse  # type: ignore
    from ._models import SpatialCoordinate  # type: ignore
    from ._models import StatesetCreatedResponse  # type: ignore
    from ._models import StatesetGetResponse  # type: ignore
    from ._models import StatesetInfoObject  # type: ignore
    from ._models import StatesetListResponse  # type: ignore
    from ._models import Step  # type: ignore
    from ._models import Stop  # type: ignore
    from ._models import StringRuleObject  # type: ignore
    from ._models import StringTypeStyleRule  # type: ignore
    from ._models import StyleRuleBase  # type: ignore
    from ._models import StylesObject  # type: ignore
    from ._models import SunGlare  # type: ignore
    from ._models import TemperatureSummary  # type: ignore
    from ._models import TemperatureSummaryPast12Hours  # type: ignore
    from ._models import TemperatureSummaryPast24Hours  # type: ignore
    from ._models import TemperatureSummaryPast6Hours  # type: ignore
    from ._models import Tickets  # type: ignore
    from ._models import TilesetDetailInfo  # type: ignore
    from ._models import TilesetListResponse  # type: ignore
    from ._models import TimeTransition  # type: ignore
    from ._models import TimeZoneByCoordinates  # type: ignore
    from ._models import TimezoneByCoordinatesResult  # type: ignore
    from ._models import TimezoneById  # type: ignore
    from ._models import TimezoneByIdResult  # type: ignore
    from ._models import TimezoneEnumWindow  # type: ignore
    from ._models import TimezoneIanaVersionResult  # type: ignore
    from ._models import TrafficFlowSegmentResult  # type: ignore
    from ._models import TrafficFlowSegmentResultFlowSegmentData  # type: ignore
    from ._models import TrafficFlowSegmentResultFlowSegmentDataCoordinates  # type: ignore
    from ._models import TrafficIncidentDetailResult  # type: ignore
    from ._models import TrafficIncidentDetailResultTm  # type: ignore
    from ._models import TrafficIncidentPoi  # type: ignore
    from ._models import TrafficIncidentPoiCbl  # type: ignore
    from ._models import TrafficIncidentPoiCtr  # type: ignore
    from ._models import TrafficIncidentPoiP  # type: ignore
    from ._models import TrafficIncidentTileResult  # type: ignore
    from ._models import TrafficIncidentViewportResult  # type: ignore
    from ._models import TrafficIncidentViewportResultViewpResp  # type: ignore
    from ._models import TrafficIncidentViewportResultViewpRespTrafficState  # type: ignore
    from ._models import TransitItineraryResponse  # type: ignore
    from ._models import TransitLineInfoResponse  # type: ignore
    from ._models import TransitObjectResult  # type: ignore
    from ._models import TransitRouteResponse  # type: ignore
    from ._models import TransitStopInfoResponse  # type: ignore
    from ._models import TransitTypeResult  # type: ignore
    from ._models import UploadDataAcceptedResponse  # type: ignore
    from ._models import UploadDataResponse  # type: ignore
    from ._models import Version  # type: ignore
    from ._models import Waypoint  # type: ignore
    from ._models import WeatherAlongRoutePrecipitation  # type: ignore
    from ._models import WeatherAlongRouteResponse  # type: ignore
    from ._models import WeatherAlongRouteSummary  # type: ignore
    from ._models import WeatherUnit  # type: ignore
    from ._models import WeatherUnitRange  # type: ignore
    from ._models import Wind  # type: ignore
    from ._models import WindDirection  # type: ignore
    from ._models import WindSpeed  # type: ignore

from ._maps_client_enums import (
    AbsoluteDirection,
    AgencyType,
    AlternativeRouteType,
    Avoid,
    ComputeTravelTimeFor,
    ConnectorSet,
    ConversionInputType,
    DatasetType,
    DestinationType,
    DominantPollutant,
    DrivingSide,
    EntityType,
    EntryPointType,
    Enum36,
    Enum68,
    GeoJSONGeometryType,
    GeofenceMode,
    GeometryType,
    GuidanceInstructionType,
    GuidanceManeuver,
    Hilliness,
    ImportDataType,
    IncidentGeometryType,
    JsonFormat,
    JunctionType,
    LatestStatusKeyword,
    LegType,
    MagnitudeOfDelay,
    MapImageStyle,
    MapImageryStyle,
    MapTileLayer,
    MapTileSize,
    MapTileStyle,
    MetroAreaDetailType,
    MetroAreaQueryType,
    ModeType,
    OpeningHours,
    OriginType,
    PollutantType,
    Quarter,
    RasterTileFormat,
    RealTimeArrivalsQueryType,
    RelativeDirection,
    RouteInstructionsType,
    RouteRepresentation,
    RouteType,
    ScheduleType,
    SearchIndexSet,
    SectionType,
    SpeedUnit,
    StaticMapLayer,
    StopQueryType,
    StyleRuleBaseType,
    TextFormat,
    TileFormat,
    TileSize,
    TilesetID,
    TimeType,
    TimezoneOptions,
    TrafficFlowSegmentStyle,
    TrafficFlowTileStyle,
    TrafficIncidentDetailStyle,
    TrafficIncidentTileStyle,
    TransitItineraryDetailType,
    TransitLineDetailType,
    TransitRouteType,
    TransitStopDetailType,
    TransitStopQueryType,
    TransitType,
    TransitTypeFilter,
    TravelMode,
    Type,
    Unit,
    UploadDataFormat,
    VehicleEngineType,
    VehicleLoadType,
    Windingness,
)

__all__ = [
    'Agency',
    'AirAndPollen',
    'AirQuality',
    'Alert',
    'AlertArea',
    'AlertDescription',
    'AlertDetail',
    'AliasCreateResponse',
    'AliasListItem',
    'AliasListResponse',
    'BatchRequestBody',
    'BatchRequestBodyBatchItemsItem',
    'BatchResponse',
    'BatchResponseSummary',
    'BooleanRuleObject',
    'BooleanTypeStyleRule',
    'BoundingBoxResponse',
    'BoundingBoxResponseResult',
    'BoundingBoxResponseSummary',
    'BoundingBoxResult',
    'BufferRequestBody',
    'BufferResponse',
    'BufferResponseSummary',
    'ClosestPointResultEntry',
    'CollectionDefinition',
    'CollectionInfo',
    'Color',
    'Concentration',
    'Content',
    'ConversionListDetailInfo',
    'ConversionListResponse',
    'Coordinate',
    'CoordinateAbbreviated',
    'CopyrightBoundingResult',
    'CopyrightCaptionResult',
    'CopyrightTileResult',
    'CopyrightWorldResult',
    'Country',
    'CountryRegion',
    'CurrentAirQualityResponse',
    'CurrentConditions',
    'CurrentConditionsResponse',
    'DailyAirQuality',
    'DailyAirQualityForecastResponse',
    'DailyForecast',
    'DailyForecastResponse',
    'DailyForecastSummary',
    'DailyIndex',
    'DailyIndicesResponse',
    'DataSources',
    'DataSourcesGeometry',
    'DatasetDetailInfo',
    'DatasetListResponse',
    'DatasetSources',
    'DayOrNight',
    'DefinitionProperties',
    'DegreeDaySummary',
    'Description',
    'Direction',
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorResponse',
    'Fares',
    'Feature',
    'FeatureCollectionGeoJSON',
    'FeatureGeoJSON',
    'FeatureStateObject',
    'FeatureStatesStructure',
    'GeoJSONFeatureCollection',
    'GeoJSONFeatureCollectionFeaturesItem',
    'GeoJSONGeometry',
    'GeofenceGeometry',
    'GeofenceResponse',
    'GetClosestPointResponse',
    'GetClosestPointSummary',
    'GetPointInPolygonResponse',
    'GetPointInPolygonSummary',
    'GreatCircleDistanceResponse',
    'GreatCircleDistanceResponseResult',
    'GreatCircleDistanceResponseSummary',
    'HazardDetail',
    'Hazards',
    'HourlyAirQualityForecastResponse',
    'HourlyForecast',
    'HourlyForecastResponse',
    'IanaId',
    'Interval',
    'IntervalSummary',
    'IpAddressToLocationResult',
    'ItineraryFare',
    'ItineraryResult',
    'LatestStatus',
    'Leg',
    'LegFare',
    'LegPoint',
    'Line',
    'LineArrival',
    'LineGroup',
    'LineString',
    'LineStringData',
    'LinesResult',
    'Link',
    'LocalSource',
    'LongRunningOperationResult',
    'MapDataDetailInfo',
    'MapDataListResponse',
    'MetroAreaInfoResponse',
    'MetroAreaResponse',
    'MetroAreaResult',
    'MinuteForecastResponse',
    'MinuteForecastSummary',
    'MultiPoint',
    'MultiPointData',
    'MultiPolygon',
    'MultiPolygonData',
    'Names',
    'NearbyTransitResponse',
    'Notification',
    'NumberRuleObject',
    'NumberTypeStyleRule',
    'Pattern',
    'PoiCategoryResponse',
    'PoiCategoryResult',
    'Point',
    'PointArray',
    'PointData',
    'PointElevationResult',
    'PointInPolygonResult',
    'PointsResult',
    'Pollutant',
    'Polygon',
    'PolygonData',
    'PostClosestPointResponse',
    'PostClosestPointSummary',
    'PostPointInPolygonResponse',
    'PostPointInPolygonSummary',
    'PrecipitationSummary',
    'PressureTendency',
    'Price',
    'QuarterDayForecast',
    'QuarterDayForecastResponse',
    'RangeObject',
    'RealTimeArrivalResult',
    'RealTimeArrivalsResponse',
    'ReferenceTimeByCoordinates',
    'ReferenceTimeById',
    'Region',
    'RegionCountry',
    'RepresentativePoint',
    'ReqClasses',
    'ResultViewport',
    'Root',
    'RouteDirectionsRequestBody',
    'RouteDirectionsRequestBodySupportingPoints',
    'RouteDirectionsResponse',
    'RouteDirectionsResult',
    'RouteDirectionsSummary',
    'RouteItineraryLeg',
    'RouteMatrixRequestBody',
    'RouteMatrixResponse',
    'RouteMatrixResult',
    'RouteMatrixResultResponse',
    'RouteMatrixSummary',
    'RouteOptimizedWaypoint',
    'RouteRange',
    'RouteRangeResponse',
    'RouteResponseReport',
    'RouteResponseReportEffectiveSetting',
    'RouteResultGuidance',
    'RouteResultInstruction',
    'RouteResultInstructionGroup',
    'RouteResultLeg',
    'RouteResultLegSummary',
    'RouteResultSection',
    'RouteResultSectionTec',
    'RouteResultSectionTecCause',
    'SearchAddressResponse',
    'SearchAddressResult',
    'SearchAddressReverseCrossStreetResponse',
    'SearchAddressReverseCrossStreetResult',
    'SearchAddressReverseCrossStreetSummary',
    'SearchAddressReverseResponse',
    'SearchAddressReverseResult',
    'SearchAddressReverseSummary',
    'SearchAddressStructuredResponse',
    'SearchAddressStructuredResult',
    'SearchAddressStructuredSummary',
    'SearchAddressSummary',
    'SearchAlongRouteRequestBody',
    'SearchAlongRouteResponse',
    'SearchAlongRouteResult',
    'SearchAlongRouteSummary',
    'SearchFuzzyResponse',
    'SearchFuzzyResult',
    'SearchFuzzySummary',
    'SearchGeometryResponse',
    'SearchGeometryResult',
    'SearchGeometrySummary',
    'SearchInsideGeometryRequestBody',
    'SearchNearbyResponse',
    'SearchNearbyResult',
    'SearchNearbySummary',
    'SearchPoiCategoryResponse',
    'SearchPoiCategoryResult',
    'SearchPoiCategorySummary',
    'SearchPoiResponse',
    'SearchPoiResult',
    'SearchPoiSummary',
    'SearchPolygonResponse',
    'SearchPolygonResult',
    'SearchResultAddress',
    'SearchResultAddressRanges',
    'SearchResultEntryPoint',
    'SearchResultPoi',
    'SearchResultPoiBrand',
    'SearchResultPoiCategorySet',
    'SearchResultPoiClassification',
    'SearchResultPoiClassificationName',
    'SearchResultPoiOpeningHours',
    'SearchResultPoiOpeningHoursTimeRange',
    'SearchResultPoiOpeningHoursTimeRangeTime',
    'SearchResultViewport',
    'SearchSummaryGeoBias',
    'SevereWeatherAlert',
    'SevereWeatherAlertsResponse',
    'SpatialCoordinate',
    'StatesetCreatedResponse',
    'StatesetGetResponse',
    'StatesetInfoObject',
    'StatesetListResponse',
    'Step',
    'Stop',
    'StringRuleObject',
    'StringTypeStyleRule',
    'StyleRuleBase',
    'StylesObject',
    'SunGlare',
    'TemperatureSummary',
    'TemperatureSummaryPast12Hours',
    'TemperatureSummaryPast24Hours',
    'TemperatureSummaryPast6Hours',
    'Tickets',
    'TilesetDetailInfo',
    'TilesetListResponse',
    'TimeTransition',
    'TimeZoneByCoordinates',
    'TimezoneByCoordinatesResult',
    'TimezoneById',
    'TimezoneByIdResult',
    'TimezoneEnumWindow',
    'TimezoneIanaVersionResult',
    'TrafficFlowSegmentResult',
    'TrafficFlowSegmentResultFlowSegmentData',
    'TrafficFlowSegmentResultFlowSegmentDataCoordinates',
    'TrafficIncidentDetailResult',
    'TrafficIncidentDetailResultTm',
    'TrafficIncidentPoi',
    'TrafficIncidentPoiCbl',
    'TrafficIncidentPoiCtr',
    'TrafficIncidentPoiP',
    'TrafficIncidentTileResult',
    'TrafficIncidentViewportResult',
    'TrafficIncidentViewportResultViewpResp',
    'TrafficIncidentViewportResultViewpRespTrafficState',
    'TransitItineraryResponse',
    'TransitLineInfoResponse',
    'TransitObjectResult',
    'TransitRouteResponse',
    'TransitStopInfoResponse',
    'TransitTypeResult',
    'UploadDataAcceptedResponse',
    'UploadDataResponse',
    'Version',
    'Waypoint',
    'WeatherAlongRoutePrecipitation',
    'WeatherAlongRouteResponse',
    'WeatherAlongRouteSummary',
    'WeatherUnit',
    'WeatherUnitRange',
    'Wind',
    'WindDirection',
    'WindSpeed',
    'AbsoluteDirection',
    'AgencyType',
    'AlternativeRouteType',
    'Avoid',
    'ComputeTravelTimeFor',
    'ConnectorSet',
    'ConversionInputType',
    'DatasetType',
    'DestinationType',
    'DominantPollutant',
    'DrivingSide',
    'EntityType',
    'EntryPointType',
    'Enum36',
    'Enum68',
    'GeoJSONGeometryType',
    'GeofenceMode',
    'GeometryType',
    'GuidanceInstructionType',
    'GuidanceManeuver',
    'Hilliness',
    'ImportDataType',
    'IncidentGeometryType',
    'JsonFormat',
    'JunctionType',
    'LatestStatusKeyword',
    'LegType',
    'MagnitudeOfDelay',
    'MapImageStyle',
    'MapImageryStyle',
    'MapTileLayer',
    'MapTileSize',
    'MapTileStyle',
    'MetroAreaDetailType',
    'MetroAreaQueryType',
    'ModeType',
    'OpeningHours',
    'OriginType',
    'PollutantType',
    'Quarter',
    'RasterTileFormat',
    'RealTimeArrivalsQueryType',
    'RelativeDirection',
    'RouteInstructionsType',
    'RouteRepresentation',
    'RouteType',
    'ScheduleType',
    'SearchIndexSet',
    'SectionType',
    'SpeedUnit',
    'StaticMapLayer',
    'StopQueryType',
    'StyleRuleBaseType',
    'TextFormat',
    'TileFormat',
    'TileSize',
    'TilesetID',
    'TimeType',
    'TimezoneOptions',
    'TrafficFlowSegmentStyle',
    'TrafficFlowTileStyle',
    'TrafficIncidentDetailStyle',
    'TrafficIncidentTileStyle',
    'TransitItineraryDetailType',
    'TransitLineDetailType',
    'TransitRouteType',
    'TransitStopDetailType',
    'TransitStopQueryType',
    'TransitType',
    'TransitTypeFilter',
    'TravelMode',
    'Type',
    'Unit',
    'UploadDataFormat',
    'VehicleEngineType',
    'VehicleLoadType',
    'Windingness',
]
